version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    labels:
      - dependencies
      - frontend

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    labels:
      - dependencies
      - web

  - package-ecosystem: cargo
    directory: /client/src-tauri
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust
